FROM node:24-alpine

WORKDIR /app

COPY package*.json .
RUN npm install

COPY angular.json .
COPY tsconfig*.json .
COPY proxy.conf.json .

EXPOSE 4200

ENTRYPOINT ["npx", "ng", "serve", "--host", "0.0.0.0", "--poll", "2000", "--proxy-config", "proxy.conf.json"]